version: '3.4'

services:
  scmss-api-server:
    container_name: scmss-api-server
    image: ${DOCKER_REGISTRY-}scmss-api-server
    build:
      context: .
      dockerfile: ScmssApiServer/Dockerfile
    depends_on:
      - scmss-db
    environment:
      - HTTP_PORTS=80
      - ConnectionStrings__AppDb=${DB_CONNECTION:-Host=scmss-db:5432;Database=${DB_NAME:-app};Username=${DB_USER:-app};Password=${DB_PASSWORD:-app}}
      - AWS_PROFILE=${AWS_PROFILE}
    ports:
      - 5000:80
    volumes:
      - ${AWS_DIR-${HOME-${userprofile}}}/.aws:/root/.aws:ro

  scmss-db:
    container_name: scmss-db
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME:-app}
      - POSTGRES_USER=${DB_USER:-app}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-app}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: ${DB_DATA_VOLUME:-scmss-backend}
